# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Charles N. Chano
tagline:          'My portfolio website.'
description:      '<p> Test/Validation Engineer <br /> Robotics Engineering M.S. <br /> Mechanical Engineering B.S.  </p>'
# <br> <a href="www.linkedin.com/in/charles-chano" target="_blank">My LinkedIn</a>
url:              https://cnchano.github.io
baseurl:          
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.
remote_theme: fongandrew/hydeout
author:
  name:           'Andrew Fong'
  url:            https://twitter.com/fongandrewc

paginate:         1
paginate_path:    'page:num' #'/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
# sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
# linkedin_badge: | 
#   <script src="https://platform.linkedin.com/badges/js/profile.js" async defer type="text/javascript"></script>
#   <div class="badge-base LI-profile-badge" data-locale="en_US" data-size="medium" data-theme="dark" data-type="VERTICAL" data-vanity="charles-chano" data-version="v1"><a class="badge-base__link LI-simple-link" href="https://pl.linkedin.com/in/charles-chano?trk=profile-badge">Charles Chano</a></div>
                              